# Auto-generated from Exploratores ibankit.js (ISO 13616 country table).
IBAN_COUNTRIES = {
    "AD": (24, 'Andorra'),
    "AE": (23, 'United Arab Emirates'),
    "AL": (28, 'Albania'),
    "AT": (20, 'Austria'),
    "AZ": (28, 'Azerbaijan'),
    "BA": (20, 'Bosnia and Herzegovina'),
    "BE": (16, 'Belgium'),
    "BG": (22, 'Bulgaria'),
    "BH": (22, 'Bahrain'),
    "BR": (29, 'Brazil'),
    "BY": (28, 'Belarus'),
    "CH": (21, 'Switzerland'),
    "CR": (22, 'Costa Rica'),
    "CY": (28, 'Cyprus'),
    "CZ": (24, 'Czech Republic'),
    "DE": (22, 'Germany'),
    "DK": (18, 'Denmark'),
    "DO": (28, 'Dominican Republic'),
    "EE": (20, 'Estonia'),
    "EG": (29, 'Egypt'),
    "ES": (24, 'Spain'),
    "FI": (18, 'Finland'),
    "FO": (18, 'Faroe Islands'),
    "FR": (27, 'France'),
    "GB": (22, 'United Kingdom'),
    "GE": (22, 'Georgia'),
    "GI": (23, 'Gibraltar'),
    "GL": (18, 'Greenland'),
    "GR": (27, 'Greece'),
    "GT": (28, 'Guatemala'),
    "HR": (21, 'Croatia'),
    "HU": (28, 'Hungary'),
    "IE": (22, 'Ireland'),
    "IL": (23, 'Israel'),
    "IS": (26, 'Iceland'),
    "IT": (27, 'Italy'),
    "JO": (30, 'Jordan'),
    "KW": (30, 'Kuwait'),
    "KZ": (20, 'Kazakhstan'),
    "LB": (28, 'Lebanon'),
    "LC": (32, 'Saint Lucia'),
    "LI": (21, 'Liechtenstein'),
    "LT": (20, 'Lithuania'),
    "LU": (20, 'Luxembourg'),
    "LV": (21, 'Latvia'),
    "MC": (27, 'Monaco'),
    "MD": (24, 'Moldova'),
    "ME": (22, 'Montenegro'),
    "MK": (19, 'North Macedonia'),
    "MR": (27, 'Mauritania'),
    "MT": (31, 'Malta'),
    "MU": (30, 'Mauritius'),
    "NL": (18, 'Netherlands'),
    "NO": (15, 'Norway'),
    "PK": (24, 'Pakistan'),
    "PL": (28, 'Poland'),
    "PS": (29, 'Palestine'),
    "PT": (25, 'Portugal'),
    "QA": (29, 'Qatar'),
    "RO": (24, 'Romania'),
    "RS": (22, 'Serbia'),
    "SA": (24, 'Saudi Arabia'),
    "SE": (24, 'Sweden'),
    "SI": (19, 'Slovenia'),
    "SK": (24, 'Slovakia'),
    "SM": (27, 'San Marino'),
    "TN": (24, 'Tunisia'),
    "TR": (26, 'Turkey'),
    "UA": (29, 'Ukraine'),
    "VG": (24, 'British Virgin Islands'),
    "XK": (20, 'Kosovo'),
}
